-- Database: sabor_db

-- CREATE DATABASE sabor_db
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'English_United States.1252'
--     LC_CTYPE = 'English_United States.1252'
--     LOCALE_PROVIDER = 'libc'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1
--     IS_TEMPLATE = False;

-- DROP DATABASE if EXISTS sabor_db;

-- REPORT

-- DROP TABLE if EXISTS report;

-- CREATE TABLE report (
--     -- report_id SERIAL PRIMARY KEY,
--     report_date DATE default null,
--     category VARCHAR(50) default null,
--     item VARCHAR(50) default null,
--     qty NUMERIC default null,
--     price_point_name VARCHAR(50) default null,
--     modifiers_applied TEXT default null,
--     -- notes TEXT default null,
--     location VARCHAR(50) default null,
--     dining_option VARCHAR(50) default null,
--     count INT default null,
--     channel VARCHAR(50) default null
-- );

-- DROP TABLE if EXISTS report_day;

-- CREATE TABLE report_day (
--     -- report_id SERIAL PRIMARY KEY,
--     report_date DATE default null,
--     category VARCHAR(50) default null,
--     item VARCHAR(50) default null,
--     qty NUMERIC default null,
--     price_point_name VARCHAR(50) default null,
--     modifiers_applied TEXT default null,
--     -- notes TEXT default null,
--     location VARCHAR(50) default null,
--     dining_option VARCHAR(50) default null,
--     count INT default null,
--     channel VARCHAR(50) default null
-- );

SELECT COUNT(*) AS total_rows FROM report WHERE item = 'Arepa & Empanada Thursday Special';
SELECT COUNT(*) AS total_rows FROM report;
select modifiers_applied from report where item = 'Three Amigos Burrito Box' limit 100;
SELECT DISTINCT item FROM report WHERE item IN ('B.Y.O. Bowl', 'B.Y.O.Bowl', 'Build Your Own Bowl', 'BYO Bowl');
SELECT DISTINCT item FROM report;

WITH expanded_ingredients AS (
    SELECT 
        item,
        qty,
        TRIM(UNNEST(STRING_TO_ARRAY(modifiers_applied, ','))) AS ingredient
    FROM report
    WHERE item = 'Three Amigos Special'
)
SELECT 
    TRIM(ingredient) AS ingredient,
    SUM(qty) AS total_count
FROM expanded_ingredients
GROUP BY ingredient
ORDER BY total_count DESC;

WITH expanded_ingredients AS (
    SELECT 
        item,
        qty,
        TRIM(UNNEST(STRING_TO_ARRAY(modifiers_applied, ','))) AS ingredient
    FROM report
    WHERE item IN ('Arepa & Empanada Thursday Special')
)
SELECT 
    TRIM(ingredient) AS ingredient,
    SUM(qty) AS total_count
FROM expanded_ingredients
GROUP BY ingredient
ORDER BY total_count DESC;

WITH expanded_ingredients AS (
    SELECT 
        TRIM(item) AS item,
        qty,
        TRIM(UNNEST(STRING_TO_ARRAY(COALESCE(modifiers_applied, ''), ','))) AS ingredient
    FROM report
    WHERE TRIM(item) IN ('Arepa & Empanada Thursday Special')
)
SELECT 
    CASE 
		-- WHEN LOWER(ingredient) ILIKE '' THEN ''
        ELSE TRIM(ingredient)
    END AS normalized_ingredient,
    SUM(qty) AS total_count
FROM expanded_ingredients
GROUP BY item, normalized_ingredient
ORDER BY item ASC, total_count DESC;

'Arepa & Empanada Thursday Special'
'Arepas Tradicional'
'B.Y.O. Bowl', 'B.Y.O.Bowl', 'Build Your Own Bowl', 'BYO Bowl'
'B.Y.O. Burrito', 'B.Y.O.Burrito', 'Build Your Own Burrito', 'BYO Burrito'
'Build Your Own Taco', 'BYO Tacos'
'Build Your Own Nachos'
'Carne Asada Fries'
'Chimi Shrimp Taco'
'Cuban Bowl'
'Gorditas'
'Quesabirria'
'Quesadilla'
'Sabor Especial Burrito'
'Sabor Nachos'
'Smash Burger Arepa', 'Smashburguer Arepa'
'Taco Salad'
'Tacos Americanos'
'Tacos Autenticos'
'Three Amigos Burrito'
'Three Amigos Special'

-- Fixed Query
WITH expanded_ingredients AS (
    SELECT 
        qty,
        TRIM(UNNEST(STRING_TO_ARRAY(modifiers_applied, ','))) AS ingredient
    FROM report
    WHERE item IN ('Quesadilla')
)
SELECT
    CASE 
        -- WHEN LOWER(ingredient) ILIKE 'Add Fries & Drink' THEN 'Add Fries & Drink'
		-- WHEN LOWER(ingredient) ILIKE 'Fries & Drink' THEN 'Fries & Drink'
		WHEN LOWER(ingredient) ILIKE 'Add Black Beans (4oz)' THEN 'Add Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Black Bns (4oz)' THEN 'Add Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Black Bns (2oz)' THEN 'Add Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Black Beans | 4 oz' THEN 'Add Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans' THEN 'Black Beans'
		WHEN LOWER(ingredient) ILIKE 'Add Black Beans' THEN 'Add Black Beans'
		-- WHEN LOWER(ingredient) ILIKE 'Add Black Beans' THEN 'Black Beans (4oz)'
		-- WHEN LOWER(ingredient) ILIKE 'Black Beans' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns (4oz)' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns (3oz)' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns (2oz)' THEN 'Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (4oz)' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (3oz)' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (2oz)' THEN 'Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 4 oz.' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 3 oz.' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 2 oz.' THEN 'Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (4 oz.)' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (3 oz.)' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans (2 oz.)' THEN 'Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 4 oz' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 3 oz' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Beans | 2 oz' THEN 'Black Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns | 4 oz' THEN 'Black Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns | 3 oz' THEN 'Black Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Black Bns | 2 oz' THEN 'Black Beans (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Cotija Cheese (1oz)' THEN 'Add Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija Cheese (0.5oz)' THEN 'Add Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija (1oz)' THEN 'Add Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija (0.5oz)' THEN 'Add Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija | 1 oz' THEN 'Add Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija | 0.5 oz' THEN 'Add Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija (1 oz.)' THEN 'Add Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cotija' THEN 'Add Cotija Cheese'
		-- WHEN LOWER(ingredient) ILIKE 'Add Cotija' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija (1oz)' THEN 'Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija Cheese (1oz)' THEN 'Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | 1 oz' THEN 'Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija (1 oz.)' THEN 'Cotija Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija (0.5oz)' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija Cheese (0.5oz)' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | 0.5 oz' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | 0.50 oz' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | .50 oz' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | .50 oz.' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | 0.50 oz.' THEN 'Cotija Cheese (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cotija | 1 oz.' THEN 'Cotija Cheese (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Corn (2oz)' THEN 'Add Corn (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Corn (1oz)' THEN 'Add Corn (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Corn (1 oz.)' THEN 'Add Corn (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn' THEN 'Corn'
		-- WHEN LOWER(ingredient) ILIKE 'Corn' THEN 'Corn (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn (2oz)' THEN 'Corn (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn (1oz)' THEN 'Corn (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn | 2 oz.' THEN 'Corn (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn | 1 oz.' THEN 'Corn (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn (2 oz.)' THEN 'Corn (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Corn (1 oz.)' THEN 'Corn (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Quinoa Rice (4oz)' THEN 'Add Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Quinoa Rice (2oz)' THEN 'Add Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Quinoa BR (4oz)' THEN 'Add Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Quinoa BR (2oz)' THEN 'Add Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Quinoa Brown Rice (4oz)' THEN 'Add Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice' THEN 'Quinoa Brown Rice'
		-- WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice (4oz)' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice (2oz)' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa BR (4oz)' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa BR (2oz)' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Rice (4oz)' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Rice (2oz)' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa (4oz)' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa (2oz)' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice | 4 oz' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice | 2 oz' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice | 4 oz.' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice | 2 oz.' THEN 'Quinoa Brown Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa BR | 4 oz.' THEN 'Quinoa Brown Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Quinoa BR | 2 oz.' THEN 'Quinoa Brown Rice (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Mexican Rice (4oz)' THEN 'Add Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mexican Rice (2oz)' THEN 'Add Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mex Rice (4oz)' THEN 'Add Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mex Rice (2oz)' THEN 'Add Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mex Rice (4 oz.)' THEN 'Add Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mexican Rice | 4 oz' THEN 'Add Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Mexican Rice | 2 oz' THEN 'Add Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice (4 oz)' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice (2 oz)' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (4oz)' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (2oz)' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (4 oz)' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (2 oz)' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice (4oz)' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice (2oz)' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice | 4 oz' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice | 2 oz' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice | 4 oz.' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice | 2 oz.' THEN 'Mexican Rice (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (4 oz.)' THEN 'Mexican Rice (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Mex Rice (2 oz.)' THEN 'Mexican Rice (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Pico de Gallo (2oz)' THEN 'Add Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico de Gallo (1oz)' THEN 'Add Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico (2oz)' THEN 'Add Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico (1oz)' THEN 'Add Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico (1 oz.)' THEN 'Add Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico | 2 oz' THEN 'Add Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico | 1 oz' THEN 'Add Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico (2 oz)' THEN 'Add Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pico' THEN 'Add Pico de Gallo'
		-- WHEN LOWER(ingredient) ILIKE 'Add Pico' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (2oz)' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (1oz)' THEN 'Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico de Gallo (2oz)' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico de Gallo (1oz)' THEN 'Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico | 2 oz' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico | 1 oz' THEN 'Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (2 oz)' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (1 oz)' THEN 'Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (2 oz.)' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico (1 oz.)' THEN 'Pico de Gallo (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico | 2 oz.' THEN 'Pico de Gallo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pico | 1 oz.' THEN 'Pico de Gallo (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Guacamole (2oz)' THEN 'Add Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Guac (2oz)' THEN 'Add Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Guac (2 oz.)' THEN 'Add Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Guacamole | 2 oz' THEN 'Add Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guac (2 oz.)' THEN 'Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guac (1 oz.)' THEN 'Guacamole (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Guac (2oz)' THEN 'Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guac (1oz)' THEN 'Guacamole (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole (2oz)' THEN 'Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole (1oz)' THEN 'Guacamole (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole | 2 oz.' THEN 'Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole | 1 oz.' THEN 'Guacamole (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole | 2 oz' THEN 'Guacamole (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Guacamole | 1 oz' THEN 'Guacamole (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Ground Beef (4oz)' THEN 'Add Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Ground Beef (2oz)' THEN 'Add Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grnd Beef (4oz)' THEN 'Add Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grnd Beef (2oz)' THEN 'Add Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grnd Beef (4 oz.)' THEN 'Add Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grnd Beef (2 oz.)' THEN 'Add Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Ground Beef | 4 oz' THEN 'Add Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef' THEN 'Ground Beef'
		-- WHEN LOWER(ingredient) ILIKE 'Ground Beef' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef (4 oz.)' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef (2 oz.)' THEN 'Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef (4oz)' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef (2oz)' THEN 'Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grnd Beef (4oz)' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grnd Beef (2oz)' THEN 'Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef | 4 oz.' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef | 2 oz.' THEN 'Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grnd Beef (4 oz.)' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grnd Beef (2 oz.)' THEN 'Ground Beef (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef | 4 oz' THEN 'Ground Beef (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Ground Beef | 2 oz' THEN 'Ground Beef (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Barbacoa (4oz)' THEN 'Add Barbacoa (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Barbacoa (2oz)' THEN 'Add Barbacoa (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa' THEN 'Barbacoa'
		-- WHEN LOWER(ingredient) ILIKE 'Barbacoa' THEN 'Barbacoa (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa (8oz)' THEN 'Barbacoa (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa (4oz)' THEN 'Barbacoa (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa (2oz)' THEN 'Barbacoa (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 8 oz.' THEN 'Barbacoa (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 4 oz.' THEN 'Barbacoa (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 2 oz.' THEN 'Barbacoa (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 8 oz' THEN 'Barbacoa (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 4 oz' THEN 'Barbacoa (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Barbacoa | 2 oz' THEN 'Barbacoa (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Al Pastor (4oz)' THEN 'Add Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Al Pastor (2oz)' THEN 'Add Al Pastor (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Al Pastor | 4 oz' THEN 'Add Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor (4oz)' THEN 'Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor (2oz)' THEN 'Al Pastor (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor | 4 oz.' THEN 'Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor | 2 oz.' THEN 'Al Pastor (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor | 4 oz' THEN 'Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor | 2 oz' THEN 'Al Pastor (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor Pork | 4 oz' THEN 'Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor Pork | 2 oz' THEN 'Al Pastor (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor Pork (4oz)' THEN 'Al Pastor (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Al Pastor Pork (2oz)' THEN 'Al Pastor (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Vegan Chorizo (4oz)' THEN 'Add Vegan Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Vegan Chorizo (2oz)' THEN 'Add Vegan Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo' THEN 'Vegan Chorizo'
		-- WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo' THEN 'Vegan Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo (4oz)' THEN 'Vegan Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo (2oz)' THEN 'Vegan Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo | 4 oz.' THEN 'Vegan Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Vegan Chorizo | 2 oz.' THEN 'Vegan Chorizo (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Chorizo (4oz)' THEN 'Add Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chorizo (2oz)' THEN 'Add Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chorizo | 4 oz' THEN 'Add Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chorizo (4 oz.)' THEN 'Add Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo' THEN 'Chorizo'
		-- WHEN LOWER(ingredient) ILIKE 'Chorizo' THEN 'Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo (4oz)' THEN 'Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo (2oz)' THEN 'Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo (4 oz.)' THEN 'Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo (2 oz.)' THEN 'Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo | 4 oz.' THEN 'Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo | 2 oz.' THEN 'Chorizo (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo | 4 oz' THEN 'Chorizo (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Chorizo | 2 oz' THEN 'Chorizo (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Veggies (4oz)' THEN 'Add Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Veggies (2oz)' THEN 'Add Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Veg (4oz)' THEN 'Add Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Veg (2oz)' THEN 'Add Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Veg (4 oz.)' THEN 'Add Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Veg (2 oz.)' THEN 'Add Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Veg (4oz)' THEN 'Add Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Veg | 4 oz' THEN 'Add Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies' THEN 'Grilled Veggies'
		-- WHEN LOWER(ingredient) ILIKE 'Grilled Veggies' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Veg (4oz)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Veg (2oz)' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies (4oz)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies (2oz)' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veg (4oz)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veg (2oz)' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Veg (4 oz.)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Veg (2 oz.)' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable | 4 oz.' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable | 2 oz.' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable | 4 oz' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable | 2 oz' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable (4oz)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Vegetable (2oz)' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies | 4 oz.' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies | 2 oz.' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies | 4 oz' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggies | 2 oz' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veg | 4 oz' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veg | 2 oz' THEN 'Grilled Veggies (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggie (4oz)' THEN 'Grilled Veggies (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Veggie (2oz)' THEN 'Grilled Veggies (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Chicken (4oz)' THEN 'Add Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Chick (4oz)' THEN 'Add Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Chick (4oz)' THEN 'Add Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Chick (2oz)' THEN 'Add Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Chick (2oz)' THEN 'Add Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grilled Chicken | 4 oz' THEN 'Add Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Grill Chick (4 oz.)' THEN 'Add Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken' THEN 'Grilled Chicken'
		-- WHEN LOWER(ingredient) ILIKE 'Grilled Chicken' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken (4 oz.)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken (2 oz.)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken (4oz)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken (2oz)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chick (4oz)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chick (2oz)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chick (4oz)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chick (2oz)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chicken (4oz)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chicken (2oz)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken | 4 oz.' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken | 2 oz.' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chick (4 oz.)' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grill Chick (2 oz.)' THEN 'Grilled Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken | 4 oz' THEN 'Grilled Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Chicken | 2 oz' THEN 'Grilled Chicken (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Refried Beans (4oz)' THEN 'Add Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Refried Beans (2oz)' THEN 'Add Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Refried (4oz)' THEN 'Add Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Refried (2oz)' THEN 'Add Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Refried Beans(4oz)' THEN 'Add Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Refried Beans' THEN 'Add Refried Beans'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans' THEN 'Refried Beans'
		-- WHEN LOWER(ingredient) ILIKE 'Refried Beans' THEN 'Refried Beans (4oz)'
		-- WHEN LOWER(ingredient) ILIKE 'Add Refried Beans' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (4oz)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (3oz)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (2oz)' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (4oz)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (3oz)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (2oz)' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 4 oz.' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 3 oz.' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 2 oz.' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 4 oz.' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 3 oz.' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 2 oz.' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 4 oz' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 3 oz' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried | 2 oz' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (4 oz.)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (3 oz.)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans (2 oz.)' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans(4oz)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans(3oz)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans(2oz)' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 4 oz' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 3 oz' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried Beans | 2 oz' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (4 oz.)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (3 oz.)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (2 oz.)' THEN 'Refried Beans (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (4oz.)' THEN 'Refried Beans (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (3oz.)' THEN 'Refried Beans (3oz)'
		WHEN LOWER(ingredient) ILIKE 'Refried (2oz.)' THEN 'Refried Beans (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Chicken (4oz)' THEN 'Add Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Chicken (2oz)' THEN 'Add Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shred Chick (4oz)' THEN 'Add Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shred Chick (2oz)' THEN 'Add Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shred Chick (4 oz.)' THEN 'Add Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add ShreddedChick (4oz)' THEN 'Add Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Chick (2oz)' THEN 'Add Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Chicken | 4 oz' THEN 'Add Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Chicken | 2 oz' THEN 'Add Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken' THEN 'Shredded Chicken'
		-- WHEN LOWER(ingredient) ILIKE 'Shredded Chicken' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken (4oz)' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken (2oz)' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chick (4oz)' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chick (2oz)' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 4 oz' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 2 oz' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 4 oz.' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 2 oz.' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 4oz' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken | 2oz' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chick (4oz)' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chick (2oz)' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'ShreddedChick (4oz)' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'ShreddedChick (2oz)' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chick (4 oz.)' THEN 'Shredded Chicken (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chick (2 oz.)' THEN 'Shredded Chicken (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chicken (2 oz.)' THEN 'Shredded Chicken (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Steak (4oz)' THEN 'Add Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Steak (2oz)' THEN 'Add Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Steak | 4 oz' THEN 'Add Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Steak | 2 oz' THEN 'Add Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Steak (4 oz.)' THEN 'Add Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Steak (2 oz.)' THEN 'Add Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak (4oz)' THEN 'Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak (2oz)' THEN 'Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak | 4 oz' THEN 'Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak | 2 oz' THEN 'Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak (4 oz.)' THEN 'Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak (2 oz.)' THEN 'Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak | 4 oz.' THEN 'Steak (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Steak | 2 oz.' THEN 'Steak (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Grilled Beef | 2 oz.' THEN 'Steak (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Cheese (2oz)' THEN 'Add Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Cheese (1oz)' THEN 'Add Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shred Chz (2oz)' THEN 'Add Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shred Chz (1oz)' THEN 'Add Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Cheese | 2 oz' THEN 'Add Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shredded Cheese | 1 oz' THEN 'Add Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese' THEN 'Shredded Cheese'
		-- WHEN LOWER(ingredient) ILIKE 'Shredded Cheese' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chz (2oz)' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shred Chz (1oz)' THEN 'Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese (2oz)' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese (1oz)' THEN 'Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese | 2 oz' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese | 1 oz' THEN 'Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese | 2 oz.' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese | 1 oz.' THEN 'Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese (2 oz.)' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cheese (1 oz.)' THEN 'Shredded Cheese (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chesse | 2 oz.' THEN 'Shredded Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Chesse | 1 oz.' THEN 'Shredded Cheese (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Shrimp (4oz)' THEN 'Add Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shrimp (2oz)' THEN 'Add Shrimp (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shrimp | 4 oz' THEN 'Add Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Shrimp (2 oz.)' THEN 'Add Shrimp (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp' THEN 'Shrimp'
		-- WHEN LOWER(ingredient) ILIKE 'Shrimp' THEN 'Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (8oz)' THEN 'Shrimp (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (4oz)' THEN 'Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (2oz)' THEN 'Shrimp (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 8 oz.' THEN 'Shrimp (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 4 oz.' THEN 'Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 2 oz.' THEN 'Shrimp (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 8 oz' THEN 'Shrimp (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 4 oz' THEN 'Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp | 2 oz' THEN 'Shrimp (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (8 oz.)' THEN 'Shrimp (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (4 oz.)' THEN 'Shrimp (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Shrimp (2 oz.)' THEN 'Shrimp (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE '%beef% %emp%' THEN 'Ground Beef Empanada'
		WHEN LOWER(ingredient) ILIKE '%chicken% %emp%' THEN 'Chicken Empanada'
		WHEN LOWER(ingredient) ILIKE '%chorizo% %emp%' THEN 'Chorizo Empanada'
		WHEN LOWER(ingredient) ILIKE '%guava% %emp%' THEN 'Pineapple Guava Empanada'
		WHEN LOWER(ingredient) ILIKE '%veggie% %emp%' THEN 'Veggie Empanada'
		WHEN LOWER(ingredient) ILIKE '%bean% %emp%' THEN 'Black Bean Empanada'
		WHEN LOWER(ingredient) ILIKE '%barbacoa% %emp%' THEN 'Barbacoa Empanada'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Cheese | 4 oz.' THEN 'Cheese (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Cheese | 2 oz.' THEN 'Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cheese (4oz)' THEN 'Cheese (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Cheese (2oz)' THEN 'Cheese (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cheese' THEN 'Cheese'
		-- WHEN LOWER(ingredient) ILIKE 'Cheese' THEN 'Cheese (4oz)'
		-- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Queso (4oz)' THEN 'Add Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Queso (2oz)' THEN 'Add Queso (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Queso | 4 oz' THEN 'Add Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Queso | 2 oz' THEN 'Add Queso (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Queso' THEN 'Add Queso'
		WHEN LOWER(ingredient) ILIKE 'Queso' THEN 'Queso'
		-- WHEN LOWER(ingredient) ILIKE 'Queso' THEN 'Queso (2oz)'
		-- WHEN LOWER(ingredient) ILIKE 'Add Queso' THEN 'Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso (4oz)' THEN 'Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso (2oz)' THEN 'Queso (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso | 4 oz.' THEN 'Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso | 2 oz.' THEN 'Queso (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso (4 oz.)' THEN 'Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso (2 oz.)' THEN 'Queso (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso | 4 oz' THEN 'Queso (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso | 2 oz' THEN 'Queso (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Bell Pepper (2oz)' THEN 'Add Bell Pepper (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Bell Pepper (1oz)' THEN 'Add Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Bell Pepper | 1 oz' THEN 'Add Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Bell Pepper (1 oz.)' THEN 'Add Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper (2oz)' THEN 'Bell Pepper (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper (1oz)' THEN 'Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper | 2 oz.' THEN 'Bell Pepper (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper | 1 oz.' THEN 'Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper | 2 oz' THEN 'Bell Pepper (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper | 1 oz' THEN 'Bell Pepper (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper (2 oz.)' THEN 'Bell Pepper (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Bell Pepper (1 oz.)' THEN 'Bell Pepper (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Chimichurri (2oz)' THEN 'Add Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chimichurri (1oz)' THEN 'Add Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chimichurri | 2 oz' THEN 'Add Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Chimichurri | 1 oz' THEN 'Add Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri' THEN 'Chimichurri'
		-- WHEN LOWER(ingredient) ILIKE 'Chimichurri' THEN 'Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri (1oz)' THEN 'Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri (1 oz.)' THEN 'Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri | 2 oz' THEN 'Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri | 1 oz' THEN 'Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri | 2 oz.' THEN 'Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichurri | 1 oz.' THEN 'Chimichurri (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichuri | 2 oz.' THEN 'Chimichurri (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Chimichuri | 1 oz.' THEN 'Chimichurri (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Cilantro (0.5oz)' THEN 'Add Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cilantro (0.25oz)' THEN 'Add Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cilantro | 0.5 oz' THEN 'Add Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cilantro | 0.25 oz' THEN 'Add Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro' THEN 'Cilantro'
		-- WHEN LOWER(ingredient) ILIKE 'Cilantro' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (2oz)' THEN 'Cilantro (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (0.5oz)' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (0.25oz)' THEN 'Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 2 oz' THEN 'Cilantro (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 0.5 oz' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 0.25 oz' THEN 'Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 0.25 oz.' THEN 'Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (2 oz.)' THEN 'Cilantro (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (0.5 oz.)' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro (0.25 oz.)' THEN 'Cilantro (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | .5 oz.' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 0.5  oz.' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | 0.50 oz.' THEN 'Cilantro (0.5oz)'
		WHEN LOWER(ingredient) ILIKE 'Cilantro | .25 oz.' THEN 'Cilantro (0.25oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Curtido (2oz)' THEN 'Add Curtido (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Curtido (1oz)' THEN 'Add Curtido (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Curtido | 2 oz' THEN 'Add Curtido (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Curtido (2oz)' THEN 'Curtido (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Curtido (1oz)' THEN 'Curtido (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Curtido | 2 oz' THEN 'Curtido (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Curtido | 1 oz' THEN 'Curtido (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Lime (1ea)' THEN 'Add Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Add Lime  (1ea)' THEN 'Add Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Add Lime (1)' THEN 'Add Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Lime (1ea)' THEN 'Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Lime  (1ea)' THEN 'Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Lime (1)' THEN 'Lime (1ea)'
		WHEN LOWER(ingredient) ILIKE 'Lime | 1 Each' THEN 'Lime (1ea)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Mixed Greens' THEN 'Mixed Greens'
		WHEN LOWER(ingredient) ILIKE 'Add Mixed Greens' THEN 'Add Mixed Greens'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Onion (2oz)' THEN 'Add Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Onion (1oz)' THEN 'Add Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Onion | 2 oz' THEN 'Add Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Onion | 1 oz' THEN 'Add Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion' THEN 'Onion'
		-- WHEN LOWER(ingredient) ILIKE 'Onion' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion (2oz)' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion (1oz)' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion | 2 oz.' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion | 1 oz.' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion (2 oz.)' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion (1 oz.)' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion | 2 oz' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onion | 1 oz' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions (2 oz.)' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions (1 oz.)' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions | 2 oz.' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions | 1 oz.' THEN 'Onion (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions (2oz)' THEN 'Onion (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Onions (1oz)' THEN 'Onion (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Slice Avocado (1/2))' THEN 'Add Slice Avocado (1/2)'
		WHEN LOWER(ingredient) ILIKE 'Add Slice Avocado (1/2)' THEN 'Add Slice Avocado (1/2)'
		WHEN LOWER(ingredient) ILIKE 'Add Slice Avocado (1/4)' THEN 'Add Slice Avocado (1/4)'
		WHEN LOWER(ingredient) ILIKE 'Add Avocado (1/2)' THEN 'Add Slice Avocado (1/2)'
		WHEN LOWER(ingredient) ILIKE 'Add Avocado (1/4)' THEN 'Add Slice Avocado (1/4)'
		WHEN LOWER(ingredient) ILIKE 'Add Sliced Avocado (1/2)' THEN 'Add Slice Avocado (1/2)'
		WHEN LOWER(ingredient) ILIKE 'Add Sliced Avocado (1/4)' THEN 'Add Slice Avocado (1/4)'
		WHEN LOWER(ingredient) ILIKE 'Slice Avocado (1/4)' THEN 'Slice Avocado (1/4)'
		WHEN LOWER(ingredient) ILIKE 'Slice Avocado (1/2)' THEN 'Slice Avocado (1/2)'
		WHEN LOWER(ingredient) ILIKE 'Sliced Avocado (1/4)' THEN 'Slice Avocado (1/4)'
		WHEN LOWER(ingredient) ILIKE 'Sliced Avocado (1/2)' THEN 'Slice Avocado (1/2)'
		-- WHEN LOWER(ingredient) ILIKE 'avocado (1/2)' THEN 'Slice Avocado (1/2)'
		-- WHEN LOWER(ingredient) ILIKE 'avocado (1/4)' THEN 'Slice Avocado (1/4)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Sour Cream (1oz)' THEN 'Add Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Sour Cream (1 oz.)' THEN 'Add Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Sour Cream | 1 oz' THEN 'Add Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Sour Cream' THEN 'Add Sour Cream'
		-- WHEN LOWER(ingredient) ILIKE 'Add Sour Cream' THEN 'Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream (4oz)' THEN 'Sour Cream (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream (1oz)' THEN 'Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream | 4 oz.' THEN 'Sour Cream (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream | 1 oz.' THEN 'Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream (4 oz.)' THEN 'Sour Cream (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream (1 oz.)' THEN 'Sour Cream (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream | 4 oz' THEN 'Sour Cream (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream | 1 oz' THEN 'Sour Cream (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Tomato (2oz)' THEN 'Add Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Tomato (1oz)' THEN 'Add Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Tomato | 2 oz' THEN 'Add Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Tomato | 1 oz' THEN 'Add Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato' THEN 'Tomato'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes (2oz)' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes (1oz)' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato (2oz)' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato (1oz)' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato | 2 oz' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato | 1 oz' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato (2 oz.)' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato (1 oz.)' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes (2 oz.)' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes (1 oz.)' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes | 2 oz.' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomatoes | 1 oz.' THEN 'Tomato (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato | 2 oz.' THEN 'Tomato (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tomato | 1 oz.' THEN 'Tomato (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Fish (4oz)' THEN 'Add Fish (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Fish (2oz)' THEN 'Add Fish (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish (4oz)' THEN 'Fish (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish (2oz)' THEN 'Fish (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish | 4 oz.' THEN 'Fish (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish | 2 oz.' THEN 'Fish (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish | 4 oz' THEN 'Fish (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Fish | 2 oz' THEN 'Fish (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Tofu (4oz)' THEN 'Add Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Tofu (2oz)' THEN 'Add Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero (4oz)' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero (8oz)' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero (4oz)' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero (2oz)' THEN 'Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu (8oz)' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu (4oz)' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu (2oz)' THEN 'Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 8 oz.' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 4 oz.' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 2 oz.' THEN 'Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 8 oz' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 4 oz' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu | 2 oz' THEN 'Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 8 oz.' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 4 oz.' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 2 oz.' THEN 'Tofu Ranchero (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 8 oz' THEN 'Tofu Ranchero (8oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 4 oz' THEN 'Tofu Ranchero (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Tofu Ranchero | 2 oz' THEN 'Tofu Ranchero (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Jalapeno (2oz)' THEN 'Add Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Jalapeno (1oz)' THEN 'Add Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Jalapeno | 2 oz' THEN 'Add Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Jalapeno | 1 oz' THEN 'Add Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Jalapeno (2 oz.)' THEN 'Add Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno (2oz)' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno (1oz)' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno (2 oz.)' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno (1 oz.)' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno | 2 oz.' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno | 1 oz.' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeño | 2 oz.' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeño | 1 oz.' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno | 2 oz' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapeno | 1 oz' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapenos | 2 oz' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapenos | 1 oz' THEN 'Jalapeno (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapenos (2oz)' THEN 'Jalapeno (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Jalapenos (1oz)' THEN 'Jalapeno (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Cabbage (2oz)' THEN 'Add Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cabbage (1oz)' THEN 'Add Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Cabbage | 1 oz' THEN 'Add Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage (2oz)' THEN 'Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage (1oz)' THEN 'Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage | 2 oz.' THEN 'Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage | 1 oz.' THEN 'Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage | 2 oz' THEN 'Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Cabbage | 1 oz' THEN 'Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cabbage | 2 oz' THEN 'Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cabbage | 1 oz' THEN 'Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cabbage (2oz)' THEN 'Cabbage (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cabbage (1oz)' THEN 'Cabbage (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Shredded Cabbage' THEN 'Cabbage'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce (2oz)' THEN 'Add Lettuce (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce (1oz)' THEN 'Add Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce (0.25oz)' THEN 'Add Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce | 1 oz' THEN 'Add Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce | 0.25 oz' THEN 'Add Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce (1 oz.)' THEN 'Add Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Lettuce (0.25 oz.)' THEN 'Add Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (2oz)' THEN 'Lettuce (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (1oz)' THEN 'Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (0.25oz)' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 2 oz.' THEN 'Lettuce (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 1 oz.' THEN 'Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 0.25 oz.' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 2 oz' THEN 'Lettuce (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 1 oz' THEN 'Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 0.25 oz' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (2 oz.)' THEN 'Lettuce (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (1 oz.)' THEN 'Lettuce (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce (0.25 oz.)' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | .2 oz.' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | 0.25' THEN 'Lettuce (0.25oz)'
		WHEN LOWER(ingredient) ILIKE 'Lettuce | .25' THEN 'Lettuce (0.25oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Pineapple (2oz)' THEN 'Add Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pineapple (1oz)' THEN 'Add Pineapple (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pineapple | 2 oz' THEN 'Add Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple' THEN 'Pineapple'
		-- WHEN LOWER(ingredient) ILIKE 'Pineapple' THEN 'Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple (2oz)' THEN 'Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple (1oz)' THEN 'Pineapple (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple | 2 oz.' THEN 'Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple | 1 oz.' THEN 'Pineapple (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple | 2 oz' THEN 'Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple | 1 oz' THEN 'Pineapple (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple (2 oz.)' THEN 'Pineapple (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pineapple (1 oz.)' THEN 'Pineapple (1oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Pork Belly (4oz)' THEN 'Add Pork Belly (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pork Belly (2oz)' THEN 'Add Pork Belly (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Add Pork Belly | 4 oz' THEN 'Add Pork Belly (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly (4oz)' THEN 'Pork Belly (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly (2oz)' THEN 'Pork Belly (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly | 4 oz.' THEN 'Pork Belly (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly | 2 oz.' THEN 'Pork Belly (2oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly | 4 oz' THEN 'Pork Belly (4oz)'
		WHEN LOWER(ingredient) ILIKE 'Pork Belly | 2 oz' THEN 'Pork Belly (2oz)'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'Add Tortilla Strips (1oz)' THEN 'Add Tortilla Strips (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Queso on the Side' THEN 'Queso on the Side'
		WHEN LOWER(ingredient) ILIKE 'Chips on the Side' THEN 'Chips on the Side'
		WHEN LOWER(ingredient) ILIKE 'Spicy Rosada' THEN 'Spicy Rosada'
		WHEN LOWER(ingredient) ILIKE 'Spicy Rosada (1 oz.)' THEN 'Spicy Rosada (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Spicy Rosada | 1 oz.' THEN 'Spicy Rosada (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Spicy Rosada (1oz)' THEN 'Spicy Rosada (1oz)'
		WHEN LOWER(ingredient) ILIKE 'Flour Tortilla' THEN 'Flour Tortilla'
		WHEN LOWER(ingredient) ILIKE 'Corn Tortilla' THEN 'Corn Tortilla'
		WHEN LOWER(ingredient) ILIKE 'Sub Yuca Fries' THEN 'Sub Yuca Fries'
		WHEN LOWER(ingredient) ILIKE 'Sub Corn Tortilla' THEN 'Sub Corn Tortilla'
		WHEN LOWER(ingredient) ILIKE 'Sub Corn Tortillas' THEN 'Sub Corn Tortilla'
		WHEN LOWER(ingredient) ILIKE 'Sub Flour Tortilla' THEN 'Sub Flour Tortilla'
		WHEN LOWER(ingredient) ILIKE 'Sub Flour Tortillas' THEN 'Sub Flour Tortilla'
		WHEN LOWER(ingredient) ILIKE 'MAKE IT A BURRITO' THEN 'Make it a Burrito'
		WHEN LOWER(ingredient) ILIKE 'MAKE IT A Bowl' THEN 'Make it a Bowl'
		WHEN LOWER(ingredient) ILIKE 'Substitute Lettuce' THEN 'Substitute Lettuce'
		WHEN LOWER(ingredient) ILIKE 'Sour Cream On the Side' THEN 'Sour Cream on the Side'
		WHEN LOWER(ingredient) ILIKE 'Add Fries & Drink' THEN 'Add Fries & Drink'
		WHEN LOWER(ingredient) ILIKE 'Fries & Drink' THEN 'Fries & Drink'
		WHEN LOWER(ingredient) ILIKE 'Quinoa Brown Rice Only' THEN 'Quinoa Brown Rice Only'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice & Quinoa Brown Rice' THEN 'Mexican Rice & Quinoa Brown Rice'
		WHEN LOWER(ingredient) ILIKE 'Mexican & Quinoa Brown Rice' THEN 'Mexican Rice & Quinoa Brown Rice'
		WHEN LOWER(ingredient) ILIKE 'Mexican Rice Only' THEN 'Mexican Rice Only'
		WHEN LOWER(ingredient) ILIKE 'Extra Broth' THEN 'Extra Broth'
		WHEN LOWER(ingredient) ILIKE 'Unsweet Tea' THEN 'Unsweet Tea'
		WHEN LOWER(ingredient) ILIKE 'Fanta Orange' THEN 'Fanta Orange'
		WHEN LOWER(ingredient) ILIKE 'Sprite' THEN 'Sprite'
		WHEN LOWER(ingredient) ILIKE 'Dr. Pepper' THEN 'Dr. Pepper'
		WHEN LOWER(ingredient) ILIKE 'Lemonade' THEN 'Lemonade'
		WHEN LOWER(ingredient) ILIKE 'Sweet Tea' THEN 'Sweet Tea'
		WHEN LOWER(ingredient) ILIKE 'Diet Coke' THEN 'Diet Coke'
		WHEN LOWER(ingredient) ILIKE 'Coke' THEN 'Coke'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
		WHEN LOWER(ingredient) ILIKE 'No Beans' THEN 'No Beans'
		WHEN LOWER(ingredient) ILIKE 'No Beans (2oz)' THEN 'No Beans'
		WHEN LOWER(ingredient) ILIKE 'No Cotija Cheese' THEN 'No Cotija Cheese'
		WHEN LOWER(ingredient) ILIKE 'no cotjia cheese' THEN 'No Cotija Cheese'
		WHEN LOWER(ingredient) ILIKE 'No Cotija' THEN 'No Cotija Cheese'
		WHEN LOWER(ingredient) ILIKE 'No Queso' THEN 'No Queso'
		WHEN LOWER(ingredient) ILIKE 'No Cheese' THEN 'No Cheese'
		WHEN LOWER(ingredient) ILIKE 'No Pico' THEN 'No Pico de Gallo'
		WHEN LOWER(ingredient) ILIKE 'No Pico de Gallo' THEN 'No Pico de Gallo'
		WHEN LOWER(ingredient) ILIKE 'No Guac' THEN 'No Guacamole'
		WHEN LOWER(ingredient) ILIKE 'No Guacamole' THEN 'No Guacamole'
		WHEN LOWER(ingredient) ILIKE 'No Sour Cream' THEN 'No Sour Cream'
		WHEN LOWER(ingredient) ILIKE 'No Lettuce' THEN 'No Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Cilantro' THEN 'No Cilantro'
		WHEN LOWER(ingredient) ILIKE 'No Tomato' THEN 'No Tomato'
		WHEN LOWER(ingredient) ILIKE 'No Lime Wedge' THEN 'No Lime Wedge'
		WHEN LOWER(ingredient) ILIKE 'No Lime' THEN 'No Lime Wedge'
		WHEN LOWER(ingredient) ILIKE 'No Plantain' THEN 'No Plantain'
		WHEN LOWER(ingredient) ILIKE 'No Broth' THEN 'No Broth'
		WHEN LOWER(ingredient) ILIKE 'No Protein' THEN 'No Protein'
		WHEN LOWER(ingredient) ILIKE 'No Rice - Substitute Lettuce' THEN 'No Rice - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Rice- Sub Lettuce' THEN 'No Rice - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Rice Sub Lettuce' THEN 'No Rice - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'no rice - sub lettuce' THEN 'No Rice - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Beans - Substitute Lettuce' THEN 'No Beans - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Beans Sub Lettuce' THEN 'No Beans - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Beans- Sub Lettuce' THEN 'No Beans - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Lettuce - Sub Cabbage' THEN 'No Lettuce - Sub Cabbage'
		WHEN LOWER(ingredient) ILIKE 'No Lettuce- Sub Cabbage' THEN 'No Lettuce - Sub Cabbage'
		WHEN LOWER(ingredient) ILIKE 'No Lettuce Sub Cabbage' THEN 'No Lettuce - Sub Cabbage'
		WHEN LOWER(ingredient) ILIKE 'No Rice' THEN 'No Rice'
		WHEN LOWER(ingredient) ILIKE 'no spring mix sub lettuce' THEN 'No Spring Mix - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Spring Mix - Sub Lettuce' THEN 'No Spring Mix - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Spring Mix- Sub Lettuce' THEN 'No Spring Mix - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'Substitute Lettuce' THEN 'No Spring Mix - Sub Lettuce'
		WHEN LOWER(ingredient) ILIKE 'No Spring Mix- Sub Cabbage' THEN 'No Spring Mix - Sub Cabbage'
		WHEN LOWER(ingredient) ILIKE 'No Spring Mix Sub Cabbage' THEN 'No Spring Mix - Sub Cabbage'
		WHEN LOWER(ingredient) ILIKE 'Not Tortilla Bowl' THEN 'No Tortilla Bowl'
		WHEN LOWER(ingredient) ILIKE 'No Tortilla Bowl' THEN 'No Tortilla Bowl'
		WHEN LOWER(ingredient) ILIKE 'No Spring Mix' THEN 'No Spring Mix'
		WHEN LOWER(ingredient) ILIKE 'No Shred Chz' THEN 'No Shredded Cheese'
		WHEN LOWER(ingredient) ILIKE 'No Shredded Cheese' THEN 'No Shredded Cheese'
		WHEN LOWER(ingredient) ILIKE 'No Rosada' THEN 'No Rosada'
		WHEN LOWER(ingredient) ILIKE 'No Rosada Sauce' THEN 'No Rosada'
		WHEN LOWER(ingredient) ILIKE 'No Chicken' THEN 'No Chicken'
		WHEN LOWER(ingredient) ILIKE 'No Chimichurri' THEN 'No Chimichurri'
		WHEN LOWER(ingredient) ILIKE 'No Onion' THEN 'No Onion'
		-- -- WHEN LOWER(ingredient) ILIKE '' THEN ''
        ELSE TRIM(LOWER(ingredient))
    END AS normalized_ingredient,
    SUM(qty) AS total_count
FROM expanded_ingredients
GROUP BY normalized_ingredient
ORDER BY total_count DESC;

-- If You Want Item-Wise Breakdown Too
-- If you still need to see which items contributed to the 
-- ingredient count but want to combine duplicates across items, use this:
WITH expanded_ingredients AS (
    SELECT 
        item,
        qty,
        TRIM(UNNEST(STRING_TO_ARRAY(modifiers_applied, ','))) AS ingredient
    FROM report
    WHERE item IN ('Smash Burger Arepa', 'Smashburguer Arepa')
)
SELECT 
    item,
    CASE 
        WHEN LOWER(ingredient) ILIKE 'Add Fries & Drink' THEN 'Fries & Drink'
		WHEN LOWER(ingredient) ILIKE 'Fries & Drink' THEN 'Fries & Drink'
        ELSE TRIM(LOWER(ingredient))
    END AS normalized_ingredient,
    SUM(qty) AS total_count
FROM expanded_ingredients
GROUP BY item, normalized_ingredient
ORDER BY normalized_ingredient, total_count DESC;





